version: '3'
services:
  pg:
    image: "postgres:alpine"
    container_name: "patagonian-challenge-postgres"
    env_file:
      - ".env"
    ports:
      - "5555:5432"
    volumes:
      - "pg:/var/lib/postgresql/data"
    restart: "always"
  test:
    image: "postgres:alpine"
    container_name: "patagonian-challenge-postgres-test"
    env_file:
      - ".env.test"
    ports:
      - "5556:5432"
    volumes:
      - "test:/var/lib/postgresql/data"
    restart: "always"
volumes:
  pg:
  test:
